### ISSUE TITLE
Sequencer plugin causes host (qtractor) to crash when setting length > 10

### ISSUE THREAD

**Issue by tcrass** [emuse/qmidiarp#9]
Not sure if this is a QMidiArp or a qtractor issue, but I'll report it here anyway...

How to reproduce:

- Create a new qtractor project
- Add a MIDI track
- Insert QMidiArp Seq as track plugin
- Open the QMidiArp Seq GUI
- Change "length" to something greater than 10
- => qtractor crashes

Observerd with self-compiled QMidiArp (commit 85c472a) in qtractor (0.9.21 AppImage) on Debian Buster.

Cheers --

Torsten

**Comment by emuse** [comment]
Hi,
Thanks for your report, but I cannot reproduce this here.
One possibility might be that you have installed LV2 plugins at different locations since you installed qmidiarp from git. I'm not sure where debian installs lv2 plugins that come with the package (/usr/lib/lv2/qmidiarp* ? That would be good. On ubuntu I've seen /usr/lib/x86_64_linux/lv2 (!) ) , and if you don't uninstall the package before there *might* be some trouble. In qtractor's mixer, can you right click on the plugin and call 'properties' and check whether it lets you go to values above 10? If not there maybe the problem described, because the seq module has extended length range since the last release. 

So either uninstall the package version and reinstall the git version,
Or rebuild the git version with --libdir=<your libdir>, make, make install.... which would overwrite the original location.

That's just a guess and about what I can think of now...

Best
Frank

**Comment by emuse** [comment]
No worries, hope it does what you want now

Frank
